version: '3.7'
services:
  legendofajax:
    container_name: legendofajax
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
networks:
  default:
    name: legendofajax
